import Link from 'next/link';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { useState } from 'react';

// Styles
import { FormContainer, Form } from '../../styles/styled_components/form';

const Login = ({ supabase, session, timeOut }) => {
	const [email, setEmail] = useState('');
	const [password, setPassword] = useState('');
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState(null);
	const [message, setMessage] = useState(null);

	const router = useRouter();

	const handleSubmit = async (e) => {
		e.preventDefault();
		const { user, error } = await supabase.auth.signInWithPassword({
			email,
			password,
		});

		if (error) {
			console.log(error);
			setLoading(false);
			setError(error.message);
			timeOut(3000).then(() => setError(''));
		} else {
			setLoading(false);
			setMessage('Logged in');
			//redirect to home page
			router.push('/');
		}
	};

	return (
		<>
			<Head>
				<title>Student Travel- login</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<FormContainer>
					<h1>Login</h1>
					{message && <p>{message}</p>}
					{error && <p>{error}</p>}
					<Form onSubmit={handleSubmit}>
						<div>
							<label htmlFor="email">Email</label>
							<input
								type="email"
								id="email"
								value={email}
								onChange={(e) => setEmail(e.target.value)}
							/>
						</div>
						<div>
							<label htmlFor="password">Password</label>
							<input
								type="password"
								id="password"
								value={password}
								onChange={(e) => setPassword(e.target.value)}
							/>
						</div>
						<button type="submit" disabled={loading}>
							{loading ? 'Loading...' : 'Login'}
						</button>
					</Form>
					<p style={{ margin: '1.3rem 0' }}>
						No Account? <Link href="/signup">Signup</Link>
					</p>

					{error && <p>{error}</p>}
				</FormContainer>
			</main>
		</>
	);
};

export default Login;
