import { useState } from 'react';
import Link from 'next/link';
import Head from 'next/head';

// Styles
import { FormContainer, Form } from '../../styles/styled_components/form';

const Signup = ({ supabase }) => {
	const [email, setEmail] = useState('');
	const [username, setUsername] = useState('');
	const [password, setPassword] = useState('');
	const [passwordConfirm, setPasswordConfirm] = useState('');
	const [alert, setAlert] = useState('');
	const [loading, setLoading] = useState(false);
	const [error, setError] = useState('');
	const [showPassword, setShowPassword] = useState(false);

	 const togglePassword = () => {
			setShowPassword(!showPassword);
		};

	const resetForm = () => {
		setEmail('');
		setUsername('');
		setPassword('');
		setPasswordConfirm('');
		setLoading(false);
		setError('');
	};

	const handleSubmit = async (e) => {
		e.preventDefault();
		setLoading(true);
		setError('');
		if (password !== passwordConfirm) {
			setError('Passwords do not match');
			setLoading(false);
			return;
		}
		if (!email || !username || !password || !passwordConfirm) {
			setError('Please fill out all fields');
			setLoading(false);
			return;
		}
		const { user, error } = await supabase.auth.signUp({
			email,
			password,
			options: {
				data: {
					username,
				},
			},
		});

		if (error) {
			console.log(error);
			setLoading(false);
			setError(error.message);
		} else {
			resetForm();
			setAlert('Check your email for the confirmation link');
		}
	};

	return (
		<>
			<Head>
				<title>Student Travel- signup</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<FormContainer>
					<h1>Signup</h1>
					{alert && <p>{alert}</p>}
					{error && <p>{error}</p>}
					<h2>Please create an account to create your planner</h2>

					<Form onSubmit={handleSubmit}>
						<div>
							<label htmlFor="email">Email</label>
							<input
								type="email"
								id="email"
								value={email}
								onChange={(e) => setEmail(e.target.value)}
							/>
						</div>
						<div>
							<label htmlFor="username">Username</label>
							<input
								type="text"
								id="username"
								value={username}
								onChange={(e) => setUsername(e.target.value)}
							/>
						</div>
						<div>
							<label htmlFor="password">Password</label>
							<input
								type="password"
								id="password"
								value={password}
								onChange={(e) => setPassword(e.target.value)}
							/>
						</div>
						<div>
							<label htmlFor="passwordConfirm">Confirm Password</label>
							<input
								type="password"
								id="passwordConfirm"
								value={passwordConfirm}
								onChange={(e) => setPasswordConfirm(e.target.value)}
							/>
						</div>
						<button type="submit" disabled={loading}>
							{loading ? 'Loading...' : 'Signup'}
						</button>
					</Form>
					<p>
						Already have an account? <Link href="/login">Login</Link>
					</p>
					{error && <p>{error}</p>}
				</FormContainer>
			</main>
		</>
	);
};

export default Signup;
