import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styled from 'styled-components';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Resolutions</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Main>
				<Container>
					<h1>This is my new Resolutions app</h1>
					<p>This is a test of styled components and next.js</p>
				</Container>
			</Main>
		</>
	);
}

const Main = styled.main`
	display: flex;
	flex-direction: column;
	align-items: center;
	justify-content: center;
	min-height: 100vh;
	padding: 0 0.5rem;
	margin: 0 3rem;
	background-color: hsl(0, 0%, 10%);
`;

const Container = styled.div`
	background-color: red;
	color: white;
	padding: 1rem;
	border-radius: 0.5rem;

	p {
		font-size: 1.5rem;
		color: hsl(0, 0%, 60%);
	}
`;
