import { useState } from 'react';
import Head from 'next/head';
import styled from 'styled-components';
import { useUser, useSupabaseClient, useSession } from '@supabase/auth-helpers-react';

// Components
import IntroForm from '../components/introduction/IntroForm';
import Introduction from '../components/introduction/Introduction';
import Navbar from '../components/navigation/Navbar';

// Styles
import { FormContainer } from '../styles/styled_components/form';

function timeOut(ms) {
	return new Promise((resolve) => setTimeout(resolve, ms));
}

export default function Home() {
	const supabase = useSupabaseClient();
	const user = useUser();
	const [message, setMessage] = useState('');
	const [error, setError] = useState(false);
	const [showNext, setShowNext] = useState(false);

	const onSubmit = async (e) => {
		e.preventDefault();

		if (!e.target[0].checked) {
			setError(true);
			setMessage(
				'You must accept the privacy policy & create an account to continue.'
			);
			timeOut(3000).then(() => setMessage(''));
			return;
		}

		setError(false);
		setMessage('Thank you for accepting the privacy policy.');
		timeOut(3000).then(() => setMessage(''));
		setShowNext(true);
	};

	console.log(user);

	return (
		<>
			<Head>
				<title>Resolutions</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Main>
				<FormContainer>
					{showNext ? <Introduction /> : <IntroForm onSubmit={onSubmit} />}

					<div className="message">
						<p className={error ? 'error' : 'success'}>{message}</p>
					</div>
				</FormContainer>
			</Main>
		</>
	);
}

const Main = styled.main`
	background-color: hsl(0, 0%, 10%);
`;

//replicon/ F)_Q2m-=q#=#QRs
